### ISSUE TITLE
Substituir link inválido por um link apropriado.

### ISSUE THREAD

**Issue by luksamuk** [commonlispbr/cl-cookbook#4]
No presente momento, existe um link inválido no Cookbook, especificamente no Capítulo 01, no arquivo `ch01-02_iniciando-repl.md`. A última estrofe do arquivo redireciona para um capítulo de Suporte de Editores de Texto. O link deve ser mudado para um correto assim que possível e, inclusive, o nome do capítulo deve mudar, caso necessário.

**Comment by ryukinix** [comment]
Tá bom

**Comment by ryukinix** [comment]
https://github.com/commonlispbr/cl-cookbook/pull/6
